### ISSUE TITLE
Unable to create secrets

### ISSUE THREAD

**Issue by jonathandietz** [jhaals/yopass#10]
**Problem:** 
Users unable to save secrets.

**Steps to reproduce:**

1. Go to main page
2. Enter data in input box
3. Click "Encrypt Message"

The screen will not update, and looking at the browser's console you can see that there is a 404 for when trying to load aes.js.

Here's the JS thats trying to load: https://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/aes.js

**Comment by jonathandietz** [comment]
This can either be loaded internally from a JS file or just find another secure location to load this JS from.

**Comment by jhaals** [comment]
Thanks for reporting this @jonathandietz!
I want to refactor the UI component at some point
