### ISSUE TITLE
What is the actual limit for encrypt message and upload file?

### ISSUE THREAD

**Issue by sheeeng** [jhaals/yopass#1007]
Generated a few random files with predefined size.

```bash
head -c 10kB </dev/urandom >10kB
head -c 9kB </dev/urandom >9kB
head -c 8kB </dev/urandom >8kB
head -c 7kB </dev/urandom >7kB
```

Tried to upload the files, but I received the below error message except for the 7kB file.

```
The encrypted message is too long.
```

It is defined as `10000` in https://github.com/jhaals/yopass/blob/master/cmd/yopass-server/main.go#L21 line.

```golang
pflag.Int("max-length", 10000, "max length of encrypted secret")
```

In another place, it is defined as `512000` in https://github.com/jhaals/yopass/blob/master/website/src/createSecret/Upload.tsx#L20 line.

```typescript
const maxSize = 1024 * 500;
```

Appreciate further clarification on these limits.

**Comment by jhaals** [comment]
Great question @sheeeng 

The actual text is not the final size as the text will be encrypted and therefore larger. The client side limit is just to put some decent limit in place but it can't actually be used to limit uploads as you could just as well call the API directly so it's really the max-length in the yopass backend which determines how large the upload can be (below 512000 for uploads currently). There's also a max what memcache accept which is the backing storage, that file limit is 1MB and can't be raised to my knowledge. I hope that helps.

**Comment by sheeeng** [comment]
@jhaals, thank you for the detailed clarification!
