### ISSUE TITLE
letss encrypt certificate

### ISSUE THREAD

**Issue by PiotrIr** [jhaals/yopass#106]
Hi,

I'm trying to change my certificate to  generated by certboot. Unfortunately I have strange issue with this as when I'm using command:

docker run -p 443:1337 -v /etc/letsencrypt/live/yopass.mydomain.com:/certs \
    --link memcached_yopass:memcache -d jhaals/yopass -memcached=memcache:11211 -tls.key=/certs/privkey.pem -tls.cert=/certs/fullchain.pem

I'm getting error message:
2019/02/14 15:47:58 Starting yopass. Listening on port 1337
2019/02/14 15:47:58 open /cert/fullchain.pem: no such file or directory

The file definitely is in in the folder and it seems accepting first one (privkey.pem). 

When I remove from the command " -tls.key=/certs/privkey.pem" of course youpass doesn't work but container starts so I guess it finds the /cert/fullchain.pem file.

I've tried to resolve this issue myself but after few hours of attempts eventually gave up.

Could you help me please?

**Comment by jhaals** [comment]
It looks like you missed an `s`in certs by reading ` 2019/02/14 15:47:58 open /cert/fullchain.pem: no such file or directory`

**Comment by PiotrIr** [comment]
Hi, no this is not the case unfortunately. I missed it only when I typed it here.

**Comment by PiotrIr** [comment]
By a way, have you ever tried to use lets encrypt with yopass? I really like yopass but so far I had to use public certificate to get it running. No luck with certbot.
