### ISSUE TITLE
yopass and lets encrypt certificate

### ISSUE THREAD

**Issue by PiotrIr** [jhaals/yopass#107]
Johan, I'm really sorry but as I'm not sure if you watch closed issues, so I opened new one.
Basically I missed "s" in certs but only in description of the issue. On the server I haven't missed it, and just in case in once I've changed certs to cert but everywhere in the command and folder. Unfortunately it didn't help. Have you tried youpass with certbot? I really like youpass but so far I used public certificate authority and now I would like to install letsencrypt. Is it possible? Unfortunately the software works in docker and I don't have too much experience with the docker so my plan was to:
1. Stop docker service
2. run certbot to get/renew certificate
3. start docker.

It should work but unfortunately youpass container doesn't seem to find my certificate.

**Comment by jhaals** [comment]
Hi @PiotrIr the problem is probably that you're trying to mount certs from `/etc/letsencrypt/live/yourdomain.com`, all certs in that directory are symbolic links to `../../archive/yourdomain` and therefore wont work inside docker.

Instead mount 
`/etc/letsencrypt/archive/yourdomain.com/`

**Comment by PiotrIr** [comment]
Thank you Johan
