### ISSUE TITLE
"Failed to store secret in database" - how to debug?

### ISSUE THREAD

**Issue by neuroserve** [jhaals/yopass#1075]
I try to set up yopass in my private Triton (https://github.com/joyent/triton) environment in a HA fashion. Thus I spawn two yopass docker containers (with two nginx instances for tls management in front of them) which should connect to an existing redis cluster.

Thus I use 
```
--database=redis --redis="redis://bla:secret@192.168.5.22:6379/4"
```
as parameters for yopass. The website is displayed, but klicking "encrypt message" shows "Failed to store secret in database" as an error message. 

Using memcached as a backend: same result.

Docker logs shows
```
open2021/09/28 08:39:19 Starting yopass server on :1337, configured Memcached address: 192.68.5.58:11211
192.168.5.54 - - [28/Sep/2021:08:50:27 +0000] "GET /locales/de-DE.json HTTP/1.0" 404 19
192.168.5.54 - - [28/Sep/2021:08:50:31 +0000] "POST /secret HTTP/1.0" 500 50
192.168.5.55 - - [28/Sep/2021:08:54:37 +0000] "GET /favicon.ico HTTP/1.0" 200 15086
192.168.5.54 - - [28/Sep/2021:09:08:50 +0000] "GET /locales/de-DE.json HTTP/1.0" 404 19
```
Are there more debug options? As I understand there is no shell included in the yopass container, correct?
Any hints are appreciated.

**Comment by boekkooi-lengoo** [comment]
Hey,
What helped me in the past was to inspect the browser traffic using https://developer.chrome.com/docs/devtools/network/ which gave me the needed info then again I have never had that specific error.

Looking at the code I see no error logging in place [for this case](https://github.com/jhaals/yopass/blob/fb3e0f9e974fb891e4d944f9f7e49a97430eba61/pkg/server/server.go#L73). 
Maybe it would be a good idea to improve this.

**Comment by neuroserve** [comment]
Using the developer tools in the browser I basically see the same "Error 500" as a response to POSTing the secret. Debug-Logging would be nice. If this was an php application I would be searching through error logs, now.

**Comment by jhaals** [comment]
Sorry to hear that you run into issues. If you check the response from devtools as @boekkooi-lengoo suggests you should be able to get some more hints to why it's failing as there's most likely some json message in the response. "Failed to store secret in database" means something goes wrong writing to the database https://github.com/jhaals/yopass/blob/master/pkg/server/server.go#L73 My hunch is that it's something to do with the redis configuration as few other things return 500. The error logs on the server could definitely be better, me or a friendly contributor will take a look at that separately.

**Comment by neuroserve** [comment]
It's not only redis - I get the same error with memcached. I've just checked the old "--link" method and that didn't work either.
```
docker run -d -p 11211:11211 --name yopamemcached --label 'com.docker.swarm.affinities=["container!=~yopa*"]' memcached
```
then
```
docker run -d -p 1337:1337 --name yopassext --link yopamemcached:memcached --label 'com.docker.swarm.affinities=["container!=~yopa*"]' myreg/yopass/yopass:2021091701 --memcached=memcached:11211
```
logs:
```
root@e3b75fc5-3621-cdd8-f9dd-c9acbf4a37e9:~# docker logs 8b784d5df619
open2021/10/05 12:32:57 Starting yopass server on :1337, configured Memcached address: memcached:11211
10.65.69.1 - - [05/Oct/2021:12:33:18 +0000] "GET / HTTP/1.1" 200 2667
10.65.69.1 - - [05/Oct/2021:12:33:18 +0000] "GET /static/js/main.7ef1f9a6.chunk.js HTTP/1.1" 200 19939
10.65.69.1 - - [05/Oct/2021:12:33:18 +0000] "GET /static/js/2.36af9b41.chunk.js HTTP/1.1" 200 1205191
10.65.69.1 - - [05/Oct/2021:12:33:19 +0000] "GET /locales/en.json HTTP/1.1" 200 4520
10.65.69.1 - - [05/Oct/2021:12:33:19 +0000] "GET /favicon.ico HTTP/1.1" 200 15086
10.65.69.1 - - [05/Oct/2021:12:33:19 +0000] "GET /locales/de-DE.json HTTP/1.1" 404 19
10.65.69.1 - - [05/Oct/2021:12:33:19 +0000] "GET /locales/de.json HTTP/1.1" 404 19
10.65.69.1 - - [05/Oct/2021:12:33:19 +0000] "GET /favicon.png HTTP/1.1" 200 14516
10.65.69.1 - - [05/Oct/2021:12:33:19 +0000] "GET /yopass.svg HTTP/1.1" 200 6686
10.65.69.1 - - [05/Oct/2021:12:33:23 +0000] "POST /secret HTTP/1.1" 500 50
```
I'd be really interested in a shell in the yopass-container to find out, whether I can reach redis or memcached from there.

**Comment by jhaals** [comment]
Hard to tell from just seeing these logs. There's some more logging in the latest version. If you want a shell for troubleshooting you could clone this repo and edit the container in the last build step to be `ubuntu` for example https://github.com/jhaals/yopass/blob/master/Dockerfile#L12

**Comment by boekkooi-lengoo** [comment]
Hey @neuroserve,

Not sure what all this means but looking at https://github.com/go-redis/redis and it's related v7 where it mentions support for sentinel by using [NewFailoverClient](https://pkg.go.dev/github.com/go-redis/redis?utm_source=godoc#NewFailoverClient) so it looks like support could be added to yopass as well probably somewhere around [pkg/server/redis.go#L17](https://github.com/jhaals/yopass/blob/cca7367f47ac1a89374a9067f34ceacdb0e70aef/pkg/server/redis.go#L17).

Hope this helps you create a PR :smile:
