### ISSUE TITLE
How to edit website files to serve yopass behind proxy?

### ISSUE THREAD

**Issue by bobbyl140** [jhaals/yopass#1081]
I am attempting to serve this behind apache as a proxy, along with another website. I saw in a previous issue that you could change the base path for the yopass website, but I don't know enough about the languages to do so. Does anyone have any advice on how I could do this? Thanks for the help.

**Comment by bobbyl140** [comment]
PS, I am serving using Docker, if that changes anything.

**Comment by flobeier** [comment]
What you could do in your scenario is to configure your Apache instance to pass through all traffic going to the desired path to the yopass instance. See here how you can do that: https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html

**Comment by bobbyl140** [comment]
@flobeier, thank you for your response. This was actually one of the ideas I had previously, but I noticed that after the base code is loaded through the proxy, some additional requests are made, specifically for the JavaScript that powers the applet. However, these are sent as the backend's URL and the client is unable to load them, resulting in a blank page. I tried proxying the path to the JavaScript as well, but then when the secret was being loaded, the URL fragment (part after the #) was not loaded, because those parts cannot be proxied. Do you have any suggestions? Thank you.

**Comment by flobeier** [comment]
Did you configure the URL accordingly using the `--url` parameter?

**Comment by bobbyl140** [comment]
So far I have used docker to serve this, but I will switch to the standalone and try the parameter. Don’t know how I missed that! I will update with how it goes. Thank you.

**Comment by bobbyl140** [comment]
After viewing the docs more closely, the `--url` parameter is for the command line client. The issue I was having was with the web browser, do you know if this would be possible to use with a browser and from behind a proxy?

**Comment by flobeier** [comment]
Oh, sorry, you are correct. I think you should be able to get it running with your setup, it should be "just" a matter of finding the right configuration. Did you use the `ProxyPassReverse` parameter in your Apache configuration too (besides `ProxyPass`)?

**Comment by bobbyl140** [comment]
I have included the `ProxyPassReverse` directive, still with the same effect. I also added my own directives for everything requested by the client, however the URL Fragments in the sharable links can't be proxied, resulting in an error. I figure there must be some workaround, but now knowing everything there is about how apache handles proxying, I couldn't figure out a way to do it.

**Comment by flobeier** [comment]
What parts aren't proxied and result in an error? And which error do you get?

**Comment by bobbyl140** [comment]
The things that aren't proxied are the files
- /locales/en.json
- /locales/en-US.json
- /yopass.svg (not needed)
- /static/js/2.8b74e213.chunk.js (and subfiles)
- /static/js/main.f1eeb299.chunk.js (and subfiles)
- /static/css/2.907a0915.chunk.css (and subfiles)

I added `ProxyPass` and `ProxyPassReverse` directives for `/static` and `/locales`, and the secret creates successfully, however when viewing the secret from its link, beginning with `/#/s/...`, the proxy doesn't see the # or anything after it, and even when adding proxy directives for `/#`, it still won't work. From my searching, the # and what goes after it is a URL Fragment and cannot be proxied.

**Comment by jhaals** [comment]
closing as proxy example is working in https://github.com/jhaals/yopass/blob/master/deploy/docker-compose/with-nginx-proxy-and-letsencrypt/docker-compose.yml `/#` is not supposed to be proxied as that would leak into logs.

**Comment by bobbyl140** [comment]
In case anyone else in my situation comes across this, I ended up having to create a subdomain for yopass to run on, so that `/` on the proxy would result in `/` on the backend yopass server. I could not for the life of me figure out how to proxy a path off of my main server, such as `/yopass` to the backend without things getting messed up. I bet there's a way to do it but I am not knowledgable with many of apache's modules. Thank you all again for the help along the way.

**Comment by gefloh** [comment]
@bobbyl140 I stumbled over the exact same problem regarding loading of the /locales (the rest is fine for me somehow). Without having looked into the code, this heavily looks like a bug to me. Going with a subdomain now too, which causes a lot more effort.
