### ISSUE TITLE
a secret with special characters cannot be viewed properly

### ISSUE THREAD

**Issue by shikarkhane** [jhaals/yopass#11]
If i submit a secret string "mystring>" via REST api, the only way to view it is by going to link 
`/secret/<key>`
Which returns a json and is not decoded.

Please allow to get via url without decrypt key i.e. below should work
`https://yopass.se/#/s/7ca6f773-c77f-11e6-89b0-0242ac110004`

My use case was to send non-technical people, secure yopass urls, so that they could collect their passwords. 
`/secret/<key>`
resulted in a json response in their browser with special characters messed up 
@jhaals

**Comment by jhaals** [comment]
Hi @shikarkhane, are you passing `mystring>` as POST data to the API? 
The later yopass releases are using client side encryption in javascript so the payload needs to be encrypted before posting to the API. Encryption/Decryption is handled by [sjcl](https://github.com/bitwiseshiftleft/sjcl)
