### ISSUE TITLE
deploy/aws-lambda doesn't work

### ISSUE THREAD

**Issue by piotr-jagiello** [jhaals/yopass#1126]
Hi,
I tried deploying Yopass in AWS Lambda but got two issues while trying to do so (Go 1.16).
After running `go build -o main`:
```
go: github.com/jhaals/yopass@v0.0.0-20210916074044-f55704ca3135 requires
github.com/gofrs/uuid@v4.1.0+incompatible: missing go.sum entry; to add it:
go mod download github.com/gofrs/uuid
```

I resolved this one by running `go mod tidy` before the build, but then got this:
```
./main.go:26:17: not enough arguments in call to server.New
	have (server.Database, int, *prometheus.Registry, bool)
	want (server.Database, int, *prometheus.Registry, bool, *zap.Logger)
```
which looks like a legitimate bug to me.

This is all happening inside the `golang:1.16-bullseye` Docker image.

Any ideas?

**Comment by piotr-jagiello** [comment]
Well, it turns out it works if I go off the commit tagged with the latest release instead of the latest commit on master, but still, it's probably a bug on master...

**Comment by piotr-jagiello** [comment]
This still happens in release 11.3.0, so far I'm workign around this by deploying backend from 11.2 and frontend from 11.3.

**Comment by jhaals** [comment]
I just pushed a fix in master that should get the backend to build for lambda. Please give it a test.

**Comment by piotr-jagiello** [comment]
It does seem to be fixed now, thanks!

**Comment by jhaals** [comment]
you're welcome!
