### ISSUE TITLE
How does Yopass decide wether to show a textbox or to download a txt file?

### ISSUE THREAD

**Issue by C4ArtZ** [jhaals/yopass#1140]
I created four secrets ("test1", "test2", "test3" and "test4") and accessed them with the one-click links. The first two and the last one were displayed on the webpage, the third was downloaded as a .txt file.
All links were created with the same default settings (one hour, one-time download and generate decryption key).

Does Yopass decide randomly what to do or is there some hidden flag?

Browsers used: Firefox 91.3.0esr and Opera GX LVL 3 (core: 80.0.4170.91)
Deployment: insecure docker compose with latest container versions

**Comment by jhaals** [comment]
There are no hidden flags, secrets uploaded as files should be displayed as files and those added to the textarea are supposed to be displayed as text. It's all based of the URL.

**Comment by boekkooi-lengoo** [comment]
I had a similar issue related to the state being sticky this should have been fixed by https://github.com/jhaals/yopass/pull/1028/files. Which is part of https://github.com/jhaals/yopass/releases/tag/11.3.0. 

@C4ArtZ what version of yopass are you using?

**Comment by C4ArtZ** [comment]
I'm not sure but it was probably 11.2.0. Couldn't find the specific version but based on the release dates of the docker hub tags it should be this one. I pulled and recrated the latest version just now and it seems to be fixed.

**Comment by jhaals** [comment]
Glad it's fixed now. Thanks for helping out @boekkooi-lengoo. Closing the issue for now.
