### ISSUE TITLE
Help to deploy yopass

### ISSUE THREAD

**Issue by AgentZoy** [jhaals/yopass#1153]
Hi 
I'm trying to install yopass on
Debian 11
I installed go1.15.15.linux-amd64.tar.gz
Checked it works
I installed memcached
When I try to deploy yopass I got next messages and cant understand what I have to do because first time in my life tru to deploy application written on go

`go: downloading github.com/jhaals/yopass v0.0.0-20211124120028-9c57cf1d1c0f
go: found github.com/jhaals/yopass/cmd/yopass in github.com/jhaals/yopass v0.0.0-20211124120028-9c57cf1d1c0f
cannot find module providing package github.com/jhaals/yopass/cmd/yopass: working directory is not part of a module
`
Can someone help me how to deploy it

I want to deploy it manually run it and install nginx or apache as reverse proxy That web interface will be available to end users

Thanks

**Comment by flobeier** [comment]
Is there a specific reason for wanting to configure everything manually? If not then I suggest giving the Docker Compose way a try as it is the easiest to get a full setup. It includes a nginx reverse proxy with SSL encryption.
