### ISSUE TITLE
Malformed UTF-8 data

### ISSUE THREAD

**Issue by RoadRunnr** [jhaals/yopass#12]
With Linux Chrome 57.0.2950.4 dev (64-bit), after entering the decoding key, nothing is shown.

The console shows this error:

```
Error: Malformed UTF-8 data         angular.js:12416
    at Object.stringify (aes.js:10)
    at init.toString (aes.js:8)
    at app.js:60
    at angular.js:10215
    at angular.js:14634
    at n.$eval (angular.js:15916)
    at n.$digest (angular.js:15727)
    at n.$apply (angular.js:16024)
    at g (angular.js:10511)
    at K (angular.js:10683)
(anonymous)	@	angular.js:12416
```

**Comment by jhaals** [comment]
Hi @RoadRunnr, I haven't seen this issue before.
Can you confirm that this is a new issue just happening in dev builds of chrome?

**Comment by RoadRunnr** [comment]
I've been using yopass only this one time when it happend to me. I therefore can't answer that question. Sorry.
