### ISSUE TITLE
Release 11.4.0 tagged as 11.3.1

### ISSUE THREAD

**Issue by grobie** [jhaals/yopass#1202]
Hey @jhaals,

hope you're doing great! While packaging yopass for Arch (https://aur.archlinux.org/packages/yopass/), my release script released the latest version as 11.3.1. While the latest released is named 11.4.0, it uses the git tag 11.3.1. Maybe best to release again as 11.4.1?

Cheers!

**Comment by jhaals** [comment]
11.4.1 is out with a tag 👍

**Comment by grobie** [comment]
Thanks!
