### ISSUE TITLE
Increase the expiration time / TTK

### ISSUE THREAD

**Issue by moritzxbe** [jhaals/yopass#1258]
Hello, I would like to use this tool but the default expiration times are not long enough. Therefore I modified the code to have another expiration time. The creation of the new secrets is working without any errors but when I want to decrypt the secret I get an error that says that the secret does not exist.
Is there any more magic behind the source code that I have missed to change?

**Comment by sylvain-reynaud** [comment]
Hello,
what modification have you done ?

**Comment by sylvain-reynaud** [comment]
Have you tried this flag ?
`--expiration string   Duration after which secret will be deleted [1h, 1d, 1w] (default "1h")`

**Comment by moritzxbe** [comment]
I build it as a docker container `docker build -t jhaals/yopass .` and started it with `docker-compose up`.

I modified the following files:
![image](https://user-images.githubusercontent.com/9870350/152853075-27655137-d35e-4df7-b453-3e9be4b8e15b.jpeg)

**Comment by moritzxbe** [comment]
Hello, I managed to figure out why this issue occurs. Memcached has  maximum value for the expectation; so if someone need more than 30 days you may have to switch to redis.
