### ISSUE TITLE
CSP is blocking font-src from self

### ISSUE THREAD

**Issue by fireba11** [jhaals/yopass#1272]
Content-Security-Policy: default-src 'self'; font-src https://fonts.gstatic.com; form-action 'self'; frame-ancestors 'none'; script-src 'self' 'unsafe-inline' https://storage.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com

Content Security Policy: The page’s settings blocked the loading of a resource at https://<>/static/media/roboto-latin-700-normal.0682ca7f74351d42bf73.woff2 (“font-src”).

You might want to add a "font-src: 'self'" there ...

**Comment by jhaals** [comment]
Hi @fireba11 

Thanks for the heads up! I've updated the CSP so that it no longer include google since the fonts are now included.
