### ISSUE TITLE
Multiple line secret message

### ISSUE THREAD

**Issue by PatrykSiwiecEG** [jhaals/yopass#1452]
Hi,
Firstly, thanks for the great app! I have one question regarding secrets containing newline characters. Is it possible to preserve newlines in secrets?

Example:
When you create a secret like this:
![image](https://user-images.githubusercontent.com/108657712/186415633-980631a9-365f-4af6-b1d1-386a7beb0a94.png)

After decryption you will get something like this:
![image](https://user-images.githubusercontent.com/108657712/186416082-01b66752-d005-4ba1-a084-77e3fc849bad.png)

Best regards,
Patryk

**Comment by bramgn** [comment]
I agree, this would be a nice-to-have feature.

**Comment by jhaals** [comment]
Thanks! Yes that's fixed by #1418 and released in the latest version that I just published. Please reopen if the problem persist  :)
