### ISSUE TITLE
yopass gets stuck on reboot of the host

### ISSUE THREAD

**Issue by fireba11** [jhaals/yopass#1456]
I'm deploying yopass on swarm, based on the docker-compose example.
Swarm doesn't really know dependencies, so yopass starts when memcached isn't ready, causing yopass to get stuck "Failed to store secret in database" untill i restart the container.
Please make that more robust ;-)

**Comment by jhaals** [comment]
Hi!

The docker-compose example is just an example and I'm unfortunately unable to invest time in making that part better. If you find some fixes to this specific problem I'm more than happy to review them in a PR. I hope you mange to get it working better 🙏

**Comment by fireba11** [comment]
It's an issue with the container not being robust agains memcached not being reachable, it just shows up regularly with the compose. It would also be an issue on k8s etc. though there a liveliness probe might be able to work around it.
