### ISSUE TITLE
Install on cPanel instance

### ISSUE THREAD

**Issue by tsmanz** [jhaals/yopass#15]
Is there a way to install on cPanel? I have tried copying the files from the public folder to my cPanel public_html directory but when I click the Encrypt Message button nothing happens.

**Comment by jhaals** [comment]
First of all, sorry for the late reply. I don't have any knowledge about cPanel, there's a jhaals/yopass docker container you can run together with memcached if you'd like to host the service yourself. There's also a aws lambda version available at https://github.com/yopass/yopass-lambda
