### ISSUE TITLE
Here is the fr.json file for France

### ISSUE THREAD

**Issue by Simon-Syd** [jhaals/yopass#1540]
hello,
We are using your software, it's great thank you !
I just translated the .json to be used by french users, so here is the file :)
in french there is 2 word for "encrypt" and "decrypt", I choose "chiffrement" because "crypté" is associated with ransomware and have a negativ reputation

Simon

`{
  "create": {
    "title": "Chiffrer votre message",
    "inputSecretLabel": "Message secret",
    "inputSecretPlaceholder": "Message à chiffrer localement dans votre navigateur",
    "buttonEncrypt": "Chriffre votre message",
    "buttonEncryptLoading": "Message à chiffrer...",
    "inputOneTimeLabel": "Téléchargement unique",
    "inputPasswordLabel": "Clé de déchiffrement personnalisée",
    "inputGenerateLabel": "Générer la clé de déchiffrement"
  },
  "upload": {
    "title": "Déposer le fichier à télécharger",
    "caption": "Le téléchargement de fichiers est conçu pour les petits fichiers tels que les clés ssh et les certificats.",
    "errorFileTooLarge": "Le fichier est trop volumineux"
  },
  "display": {
    "titleFetching": "Récupération de la base de données, veuillez patienter...",
    "titleDecrypting": "Déchiffrement, veuillez patienter...",
    "titleDecryptionKey": "Entrez la clé de déchiffrement",
    "captionDecryptionKey": "Ne rafraîchissez pas cette fenêtre car le secret pourrait être limité à un téléchargement unique.",
    "inputDecryptionKeyPlaceholder": "Clé de déchiffrement",
    "inputDecryptionKeyLabel": "Une clé de décryptage est requise, veuillez la saisir ci-dessous",
    "errorInvalidPassword": "Mot de passe invalide, veuillez réessayer",
    "buttonDecrypt": "Déchiffrer le secret"
  },
  "error": {
    "title": "Le secret n'existe pas",
    "subtitle": "Elle peut être causée par l'une des raisons suivantes.",
    "titleOpened": "Ouvert avant",
    "subtitleOpenedBefore": "Un secret peut être limité à un seul téléchargement. Il peut être perdu parce que l'expéditeur a cliqué sur ce lien avant que vous ne l'ayez consulté.",
    "subtitleOpenedCompromised": "Le secret peut avoir été compromis et lu par quelqu'un d'autre. Vous devez contacter l'expéditeur et demander un nouveau secret.",
    "titleBrokenLink": "Lien brisé",
    "subtitleBrokenLink": "Le lien doit correspondre parfaitement pour que le décryptage fonctionne, il peut manquer quelques chiffres magiques.",
    "titleExpired": "Expiré",
    "subtitleExpired": "Aucun secret n'est éternel. Tous les secrets stockés expirent et se détruisent automatiquement. La durée de vie varie d'une heure à une semaine."
  },
  "result": {
    "title": "Secret stocké dans la base de données",
    "subtitleDownloadOnce": "N'oubliez pas que les secrets ne peuvent être téléchargés qu'une seule fois, sauf indication contraire. N'ouvrez donc pas le lien vous-même.",
    "subtitleChannel": "Merci d'envoyer la clé de décryptage dans un canal de communication séparé.",
    "rowLabelOneClick": "Lien",
    "rowLabelShortLink": "Lien court",
    "rowLabelDecryptionKey": "Clé de déchiffrement"
  },
  "secret": {
    "titleFile": "Fichier téléchargé",
    "titleMessage": "Message déchiffré",
    "subtitleMessage": "Ce secret pourrait ne plus être visible, assurez-vous de le sauvegarder maintenant !",
    "buttonCopy": "Copier"
  },
  "delete": {
    "buttonDelete": "Supprimer",
    "messageDeleted": "Le secret est supprimé du serveur !",
    "dialogTitle": "Supprimer le secret ?",
    "dialogMessage": "Êtes-vous sûr de vouloir supprimer ce Secret ?",
    "dialogProgress": "Suppression...",
    "dialogConfirm": "Supprimer",
    "dialogCancel": "Annuler"
  },
  "attribution": {
    "createdBy": "Créé par",
    "translatedBy": "Translated by",
    "translatorName": "Simon Poidevin",
    "translatorLink": ""
  },
  "expiration": {
    "legend": "Le message crypté sera supprimé automatiquement après ",
    "optionOneHourLabel": "1 heure",
    "optionOneDayLabel": "1 jour",
    "optionOneWeekLabel": "1 semaine"
  },
  "features": {
    "title": "Partagez vos secrets en toute sécurité et en toute simplicité",
    "subtitle": "Yopass a été créé pour réduire la quantité de mots de passe en clair stockés dans les courriels et les conversations en ligne en cryptant et en générant un lien de courte durée qui ne peut être consulté qu'une seule fois.",
    "featureEndToEndTitle": "Chiffrement de bout en bout",
    "featureEndToEndText": "Le chiffrement et le déchiffrement sont effectués localement dans le navigateur. La clé n'est jamais stockée chez yopass.",
    "featureSelfDestructionTitle": "Autodestruction",
    "featureSelfDestructionText": "Les messages cryptés ont une durée de vie fixe et seront supprimés automatiquement après expiration.",
    "featureOneTimeTitle": "Téléchargements uniques",
    "featureOneTimeText": "Le message crypté ne peut être téléchargé qu'une seule fois, ce qui réduit le risque que quelqu'un s'empare de vos secrets.",
    "featureSimpleSharingTitle": "Partage simple",
    "featureSimpleSharingText": "Yopass génère un lien unique en un clic pour le fichier ou le message crypté. Le mot de passe de décryptage peut également être envoyé séparément.",
    "featureNoAccountsTitle": "Pas de comptes nécessaires",
    "featureNoAccountsText": "Le partage doit être rapide et facile ; aucune information supplémentaire, hormis le secret chiffré, n'est stockée dans la base de données.",
    "featureOpenSourceTitle": "Open Source Software",
    "featureOpenSourceText": "Le mécanisme de cryptage de Yopass est construit sur un logiciel libre, ce qui signifie une transparence totale avec la possibilité d'auditer et de soumettre des fonctionnalités."
  },
  "header": {
    "buttonHome": "Accueil",
    "buttonUpload": ""
  }
}
`

**Comment by jhaals** [comment]
Hi! I do not support custom translations but feel free to contribute it to the current french translation referenced at https://github.com/jhaals/yopass#translations 👏 

Thanks!
