### ISSUE TITLE
feat: added spanish translation

### ISSUE THREAD

**Issue by nbensa** [jhaals/yopass#1627]
Hello, 

to those insterested, I made a translation to spanish.

It's available at https://github.com/nbensa/yopass-spanish and it's based on the work done by https://github.com/NicolasStr and https://github.com/Anturix

For convenience, I also made a Docker image. It's available here: https://hub.docker.com/r/eneabe/yopass-spanish

I'd prefer to contribute the translation file to the main project. This would minimize the possibility of tampering the the code. Is that a possibilty?

Thanks!
Norberto

**Comment by jhaals** [comment]
Hi! You can add a reference your translation [here](https://github.com/jhaals/yopass#translations).

Cheers,
Johan
