### ISSUE TITLE
Semantic release versioning broken in Dockerhub

### ISSUE THREAD

**Issue by psalaberria002** [jhaals/yopass#1628]
Hello!

We are using renovate for automatically getting updates whenever there is a new docker image for Yopass, but it is getting confused with https://hub.docker.com/layers/jhaals/yopass/11.14.4/images/sha256-fff96adc8e737d718a8bd89550568641f83d3b7703dccf8d80e9274920125c85?context=explore. That release is 9 months old, but it has a more recent version number.

Any way we could take that release out of Dockerhub, or remove the tag?

Thank you.

**Comment by psalaberria002** [comment]
I could work around it by setting the following config btw.
```
{
      "groupName": "yopass",
      "matchPackageNames": [
        "index.docker.io/jhaals/yopass",
      ],
      "allowedVersions": "!/11\.14\.4/"
    },
```

**Comment by jhaals** [comment]
@psalaberria002 thanks for letting me know! I've deleted the old tag so you should be able to remove your workaround now 👍
