### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by davidmind** [jhaals/yopass#164]
Hi, i am a graphics designer. I will like to know if you want me to create a new logo for your project.

**Comment by jhaals** [comment]
Hi @davidmind! I'm not a designer of any sorts and would love to get a suggestion for a new logo!

**Comment by davidmind** [comment]
Ok, i will go and work with my sketch. While i come back to give you feedback.

**Comment by davidmind** [comment]
Hi, @jhaals sorry it is coming late. I am a liitle bit busy this week. After making my sketch this is what I came up with
![yoo-pass.png](https://cdn.steemitimages.com/DQmbegzMx69EG7keTZJ2sSkEY34saeAeRXz2NTjmAwnNjPM/yoo-pass.png)

**Comment by davidmind** [comment]
@jhaals are you there?

**Comment by jhaals** [comment]
Thanks for the proposal David!
I like the sharing part of the logo, perhaps drop or change something about the two keys since they are more or less forming jaws now. I would also prefer not to have gradients.

**Comment by davidmind** [comment]
OK, I will make adjustment to it as soon as possible

**Comment by davidmind** [comment]
Hi @jhaals I made a new modifications to the logo below is the preview version
![yoo-share-pres-1.png](https://cdn.steemitimages.com/DQmWcgLCCk5sCWQ8K9CoSN9CYumPyjwgGrJQfXrCi1f3oQt/yoo-share-pres-1.png)

**Comment by davidmind** [comment]
@jhaals are you there?

**Comment by davidmind** [comment]
@jhaals are you there?

**Comment by davidmind** [comment]
@jhaals did you still need the logo?

**Comment by jhaals** [comment]
Hi @davidmind, sorry for the late reply I'm away for several weeks hiking in Spain. I'm still interested however there's something that does not feel completely right with the suggestion. Please drop the background completely and go for something transparant instead. If you have other illustrations or ideas those are welcome. Thanks again.

**Comment by davidmind** [comment]
@jhaals below are few more suggestions feel free to make suggestion on colors and what you like and what you did not like about the color and logo.
![SHARE-1.png](https://cdn.steemitimages.com/DQmSwPJr6PxzjorY6H6MhEoMJjhcBDmdqnvfjqRib1fi33B/SHARE-1.png)

**Comment by ehammond** [comment]
Comment from a passerby here. Number 4 is starting to look good and even has some meaning to me related to the software.

Suggestions: Remove the outermost colored circle. Change the logo to color on white/transparent. Consider reducing the length of the connecting lines so the overall logo is less spindly.

**Comment by davidmind** [comment]
@jhaals @ehammond here is a quick preview of the logo on a white background, feel free to make suggestion on color and anything necessary.
![SHARE-2.png](https://cdn.steemitimages.com/DQmc7TakphKfRxqUgtx4Dpa9u3s3jwnJDft5YqmpnPrLU51/SHARE-2.png)

**Comment by jhaals** [comment]
Thanks for the comments and proposal 👌 I like it.

**Comment by davidmind** [comment]
Glad to hear that, which of it is your most preferred color? As I will be creating different file size while i make a pull request with the files. I will also submit a link to editable files **AI & SVG**

**Comment by jhaals** [comment]
Number 3 would be great. Thanks a lot @davidmind. Please include the svg and ai in the PR. Make it a logo folder.

**Comment by davidmind** [comment]
OK, I will do that, hope am correct with the numbering of your selected color choice.
![1560430345076](https://user-images.githubusercontent.com/37777956/59434074-b9275a00-8de2-11e9-84f9-25fa7b8da5fc.jpg)

**Comment by jhaals** [comment]
Numrering is correct, thanks for checking.

**Comment by davidmind** [comment]
ok, @jhaals i have create a pull request containing all the logo files

**Comment by jhaals** [comment]
@davidmind merged! Thanks a lot for your help with the logo 👍👍
