### ISSUE TITLE
Non-crypto-safe key generation

### ISSUE THREAD

**Issue by marcobellaccini** [jhaals/yopass#173]
It seems like keys are generated using [Math.random()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random):
https://github.com/jhaals/yopass/blob/ec6279316caec9809d75eb4884616935acd50b81/website/src/Create.tsx#L33
https://github.com/jhaals/yopass/blob/ec6279316caec9809d75eb4884616935acd50b81/website/src/Create.tsx#L149
That method cannot be used to generate cryptographically secure random data.
A method like [Crypto​.get​Random​Values()](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues) should be used instead.

**Comment by jhaals** [comment]
Thanks for the suggested improvement @marcobellaccini. I'm on vacation without a computer but I will address it when I get home 👍
