### ISSUE TITLE
Environment Variables - render.com

### ISSUE THREAD

**Issue by kbrb** [jhaals/yopass#1798]
I'm trying to run yopass on render.com. The deployment is successful but the service gives me an error "Failed to store secret in database"
I read the posts regarding this but it didn't help me. I believe the problem is with the Environment Variables.
I am sending a screenshot of what I have set up. However they are not working.
Could anyone advise me what Environment Variables I should use on render.com to make the service save to the database?
I have created a Redis database and I have the internal Redis URL there as well.
![Screenshot 2023-07-29 at 14-29-18 Cloud Application Hosting for Developers Render](https://github.com/jhaals/yopass/assets/1284611/df835d38-2b01-41c7-a8ce-25184f0a5db0)

**Comment by jhaals** [comment]
Sorry to hear that you're having issues, I don't have capacity to provide installation troubleshooting but your environment variables should not be prefixed with YOPASS.
