### ISSUE TITLE
Include Cookies in requests

### ISSUE THREAD

**Issue by nielsole** [jhaals/yopass#18]
Hi Johan,

thanks for the great software
I am running yopass behind SSO. Authentication is done via a cookie.
Unfortunately currently yopass is not sending the cookies with the request.
The field that will most likely solve this is: https://developer.mozilla.org/en-US/docs/Web/API/Request/Request `credentials: include`
I do not see any case where transmitting the cookie with the request would have negative consequences, so this might be good to make the default behaviour.

**Comment by jhaals** [comment]
Hi @nielsole!
It warms my heart that you enjoy the software :) 
Sorry for not responding earlier. I think it makes sense to include credentials from consulting the docs. I'll let this ticket remain open until I spend time on yopass the next time. If you feel like contributing I'm happy to accept your PR to https://github.com/yopass/website

Thanks again!

**Comment by jhaals** [comment]
Hi @nielsole, I assume you fixed this yourself earlier but I just wanted to let you know that I added credentials include to the website with https://github.com/yopass/website/pull/1

**Comment by nielsole** [comment]
thanks, I didn't get to properly fixing it and had a workaround running. :tada:

**Comment by jhaals** [comment]
@nielsole glad you managed to get a workaround. I quickly discovered that the fix I pushed caused yopass to fail under aws lamda because of CORS header checks and reverted not to mess things up for existing users. A workaround would be to have an environment variable during build of website to enable credentials, how does that sound?

**Comment by nielsole** [comment]
that sounds good.
