### ISSUE TITLE
yopass.se displaying "translations" before every text block

### ISSUE THREAD

**Issue by singletonerik** [jhaals/yopass#1903]
Basically, title. Every single block of text has the word "translations:"prepended.

![image](https://github.com/jhaals/yopass/assets/76495693/1f6632f7-93bf-4af9-a480-0940770fe296)

**Comment by saimadib** [comment]
How can I reproduce the issue?

**Comment by saimadib** [comment]
I think the issue is resolved!

**Comment by singletonerik** [comment]
Yes looks fixed now on my end.

**Comment by 24367dfa** [comment]
@singletonerik you might consider closing this issue then ;-)
