### ISSUE TITLE
Support for file sharing

### ISSUE THREAD

**Issue by JensRantil** [jhaals/yopass#199]
**Background:** I wanted to share a file securily with someone this morning. I ended up encrypting using `gpg --symmetric`, e-mailing the file and sending the secret through Yopass. Two issues with this:

 *  For a non-technical person this would not be doable (they would likely resort to some less good zip file format encryption algorithm).
 * Experience of sharing a file was really bad encouraging me, and others, to reinvent file sharing procedures.
   * Specifically for my solution, the encrypted file might reside in the receiving e-mail inbox without me knowing. Preferably the file should not be stored online at all after it has been downloaded by the receiver.

**Proposal:** Add support for file uploads and downloads for sharing larger secrets.

**Scope:** For simplicity, I propose only a single file can be uploaded. The submitter can easily bundle multiple files in a zip file.

**Potential workaround:** I tried to `base64` encode the file I wanted to share and paste it into Yopass. For smaller files this might work, however, Yopass responsed that my secret was too large (possible to raise this limit?).

**Discussion points:** Yopass uses memcached. memcached has default `--max-item-size=1mb` so assuming no partioning is done, that will be the upper size. That said, the memcached limit can be raised to allow larger files. I don't think raising the limit has any big implications.

**Comment by jhaals** [comment]
This does require quite a bit of changes to support and I have no plans in the short term to support this. I can recommend https://send.firefox.com/ for storing files in the meanwhile. I'm would be happy to discuss the implementation if you would be willing to work on this issue.
