### ISSUE TITLE
notify creator when secret is viewed

### ISSUE THREAD

**Issue by jhaals** [jhaals/yopass#2]

**Comment by felixbouleau** [comment]
@jhaals I like that idea. For example, I personally use Pushbullet for everything like this.

Sorry for the bump. ;) I hope you are well!

**Comment by jhaals** [comment]
Hi @felixbouleau. I'm all good thanks!
Thanks for the bump, I need to figure out a good way to implement this.

**Comment by jhaals** [comment]
Won't fix since this will complicate things too much
