### ISSUE TITLE
Feature Request: Letter highlighting

### ISSUE THREAD

**Issue by mrgohin** [jhaals/yopass#2128]
Moi,

I think most people understand the problem I want to highlight with this feature request.

Letters are not always the same on every screen. Sometimes an I or i or 1 or l or L can look the same by simply looking at them but unfortunately they don't mean the same.

Therefore I want to request making the "decryption key" better readable by coloring the different types of "bytes":

![github_yopass](https://github.com/jhaals/yopass/assets/38684218/5dea9059-26fd-43f6-86f7-efb3ec3eeafe)

Upper -> one color
Lower -> one color
Number -> one color
Symbol -> one color

So everybody not just the blind ones can better interpret and communicate them.

Kiitos

P.S.: No worries it is a worthless password ;-)

**Comment by jhaals** [comment]
Sorry for the slow response, I've been away on parental leave. Thanks for the suggestion but I don't think it's going to look that great with different colors, happy to take suggestions for another type of font as an alternative.
