### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by PiotrIr** [jhaals/yopass#22]
Hi,
I'm trying to run yopass on port 443 but setting it like below doesn't work. It does on 1337, Could you advise please?

docker run --name memcached_yopass -d memcached

docker run -p 443:443 -v /local/certs/:/certs \
    --link memcached_yopass:memcache -d jhaals/yopass -memcached=memcache:11211 -tls.key=/certs/my.key -tls.cert=/certs/my.crt

docker run -p 443:443 --link memcached_yopass:memcache -d jhaals/yopass -memcached=memcache:11211

**Comment by jhaals** [comment]
Hi @PiotrIr 

You can either map the correct port using docker with `-p 443:1337`, see https://docs.docker.com/config/containers/container-networking/

Or tell yopass to listen on port 443 with `-port 443`

**Comment by PiotrIr** [comment]
Thank you jhaals! That is perfect!
