### ISSUE TITLE
Secret TTL based on number of views

### ISSUE THREAD

**Issue by cdhunt** [jhaals/yopass#222]
Expire a secret after N views and optionally also a time-based expiration.

**Comment by jhaals** [comment]
Thanks for the suggestion, it's not possible to control the amount of views given that the secret is downloaded and then decrypted locally. It's possible to add support for additional downloads if that would satisfy your needs.

**Comment by cdhunt** [comment]
Probably. But I'm also fine keeping it single-use. Simplicity is better.
