### ISSUE TITLE
Integrating yopass with MariaDB

### ISSUE THREAD

**Issue by Rajeshwaric7** [jhaals/yopass#2272]
i am replacing Memcached with MariaDB but getting error failed to store data in database"

When checked logs in DB pod
:"server/server.go:80","msg":"Unable to store secret","error":"memcache: no servers configured or available","stacktrace":"github.com/jhaals/yopass/pkg/server.(*Server).createSecret\n\t/yopass/pkg/server/server.go:80

Is this application restricted to use Redis and Memcached only?

Please help here.

**Comment by eponerine** [comment]
I swear that MariaDB used to be listed, but perhaps I'm suffering from Mandela Effect:
https://www.verywellmind.com/what-is-the-mandela-effect-4589394

**Comment by eponerine** [comment]
Related issue :)

https://github.com/jhaals/yopass/issues/1125

**Comment by Rajeshwaric7** [comment]
Team, i have connected to Azure cache Redis instead Mariadb and still same error

{"level":"error","ts":1715149906.388099,"caller":"server/server.go:80","msg":"Unable to store secret","error":"memcache: no servers configured or available","stacktrace":"github.com/jhaals/yopass/pkg/server.(*Server).createSecret\n\t/yopass/pkg/server/server.go:80\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\ngithub.com/jhaals/yopass/pkg/server.newMetricsMiddleware.func1.1\n\t/yopass/pkg/server/server.go:228\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212\ngithub.com/jhaals/yopass/pkg/server.SecurityHeadersHandler.func1\n\t/yopass/pkg/server/server.go:198\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\ngithub.com/gorilla/handlers.loggingHandler.ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/handlers@v1.5.2/logging.go:47\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2936\nnet/http.(*conn).serve\n\t/usr/


i am following this doc as a reference to connect to the Redis cache DB using env as mentioned in below screenshot. Please assist on this.

https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-tutorial-aks-get-started#tutorial-connect-to-azure-cache-for-redis-from-your-application-hosted-on-azure-kubernetes-service

![image](https://github.com/jhaals/yopass/assets/116628713/2ce3c215-6ede-43b7-af3b-256b451c4b93)
