### ISSUE TITLE
Build via dockerfile fails

### ISSUE THREAD

**Issue by SiriusXT** [jhaals/yopass#2283]
I try to build docker from dockerfile but I get error:
error vite@5.2.11: The engine "node" is incompatible with this module. Expected version "^18.0.0 || >=20.0.0". Got "16.20.2"

**Comment by Rajeshwaric7** [comment]
@SiriusXT you need to change the Line no 7 as below, it will work.
FROM node:18 as website

**Comment by jhaals** [comment]
Should be fixed now, thanks for reporting
