### ISSUE TITLE
Proxying under subpath url leads to missing / in the secret links

### ISSUE THREAD

**Issue by wiebel** [jhaals/yopass#229]
I have yopass runing under https://my.site.tld/yopass/ eveything is working fine but the generated secret links are like:
https://my.site.tld/yopass#/s/<LONG_HASH> instead of 
https://my.site.tld/yopass/#/s/<LONG_HASH>.
When I manually edit the URL it works just fine. Could you introduce some baseurl parameter or something?

**Comment by jhaals** [comment]
Hi @wiebel, it’s possible to set the URL for both front end and backend but you’ll have to build the container yourself since the website is static, see the readme under the website directory. Best of luck!
