### ISSUE TITLE
JSON.parse : unexpected END OF DATA

### ISSUE THREAD

**Issue by hxm-cpp** [jhaals/yopass#2403]
after deploying https://github.com/jhaals/yopass/pull/2402
![image](https://github.com/user-attachments/assets/30d567fb-6b3b-4286-918d-7de726fe4891)

**Comment by jhaals** [comment]
Sorry I don't have enough information here to actually help you. You have to check your browser network tab to figure this out but this is likely not caused by that PR specifically.
