### ISSUE TITLE
File Encryption

### ISSUE THREAD

**Issue by tolidano** [jhaals/yopass#265]
It would be great to send someone a link to an encrypted blob read from a file.
In this case, the blob would be stored in the dynamo table

See a demo of how this works elsewhere here: https://demo.tutorialzine.com/2013/11/javascript-file-encrypter/

We can use CryptoJS to allow the user to select a file, it will be encrypted client-side in the browser, we can then base64 encode the file and compute a sha1, and ship both to DynamoDB so the URL becomes the sha1/random-decrypt-key and then at the other end, it downloads the file out of Dynamo.

**Comment by tolidano** [comment]
Actually, it looks like you can use SJCL to do it, and avoid an additional import: https://stackoverflow.com/questions/26734033/encrypting-files-with-sjcl-client-side

**Comment by tolidano** [comment]
Since the decryption will take place in the browser, will need this to download the file (and some caveats on which browsers/versions will support it: https://github.com/eligrey/FileSaver.js

**Comment by jhaals** [comment]
Thanks for the suggestion @tolidano, I'm sure some basic file encryption can be address but there are some limitations in the storage backends so the initial implementation of this would probably be small files.

**Comment by tolidano** [comment]
Totally. The 10k limit would still apply. But for small things like certificates, keys, license files, and the sort, this would work great. Larger files could be encrypted with 4K keys and transferred independently and this used for the key transfer only.

**Comment by jhaals** [comment]
Smaller files sounds will be a good initial scope for this project. Supporting larger files would be an effort that require investments in other storage options. I'll look into this when I get some spare time 👍

**Comment by jhaals** [comment]
This is currently in master and available in under /upload and will be available in the next release.
I'm a bit hesitant to put this in the UI since the upload size is so limited.
