### ISSUE TITLE
Possible to remove destruction of secrets?

### ISSUE THREAD

**Issue by theitteam** [jhaals/yopass#293]
Hi Johan,

First of all, Great work! This is very impressive!

Is it possible to change the code to disable the destruction of secrets when viewed? 
We're looking at deploying this internally, but in testing have found many people click the link by accident before distributing.

Obviously, if this is fundamentally impossible - we'll deal with it :) 

Many thanks!

**Comment by jhaals** [comment]
Hi @theitteam, 
First of all great nickname and thank you!

There's currently no built in support in Yopass to allow for multiple downloads. Short term; tell your users to read the instructions saying "don't click this link yourself", I know it's tempting to click those but it's a trade off allowing multiple downloads :) I most likely add this feature in the future.

Best,
Johan

**Comment by NickJongens** [comment]
Thanks Johan, 

We're a small MSP in New Zealand :) I was attempting to learn more about how the secrets are destroyed when clicking the link in order to re-write the code to remove the process. If it was to destroy itself after a week anyway, we'd be over the moon. 

Do you have a donation page of any sort?

**Comment by jhaals** [comment]
Hi @NickJongens,
The removal happens in the API server before returning a response. I will take a look at adding support for this in the upcoming release so the feature should be available shortly.

I actually created a Github donations page very recently https://github.com/sponsors/jhaals Donations are welcome :)
