### ISSUE TITLE
Corrupted archives after downloading

### ISSUE THREAD

**Issue by kuzabi** [jhaals/yopass#346]
Hello,
I tested a little bit an file uploading feature and I noticed a problem with sharing zip/7z archives.
After uploading and downloading an archive become corrupted and unreadable.

I attach a sample zip files with almost empty txt file inside and same files after being downloaded.

Sharing file is great feature even for small files (this is enough for sharing certificates or VPN's profiles) when it's working correctly. 😄 

Regards.

[sample.zip](https://github.com/jhaals/yopass/files/4053590/sample.zip)
[sample-downloaded.zip](https://github.com/jhaals/yopass/files/4053593/sample-downloaded.zip)

**Comment by jhaals** [comment]
Thanks for reporting. 

I have been able to reproduce this problem and will look into it when I have some spare time 👍

**Comment by jhaals** [comment]
fixed by #364
