### ISSUE TITLE
Can't exec sh into yopass container

### ISSUE THREAD

**Issue by DonMcCoy** [jhaals/yopass#414]
Hi,
First thanks for the great app.
I have a problem executing into yopass container, I tried the following without avail:
`docker exec -ti deploy_yopass_1 /bin/sh`
`docker exec -ti deploy_yopass_1 /bin/bash`

It seems that i can't find any installed shell in the docker container.

**Comment by jhaals** [comment]
Hi @DonMcCoy, there are no shell in the container. If you want a shell use the yopass Dockerfile as a base and substitute distroless with your OS of choice :)
