### ISSUE TITLE
Error running: multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by Pandemic21** [jhaals/yopass#432]
I've (I think) installed the dependencies, but when I try to run it I get this:

```# go run jhaals/yopass/cmd/yopass/main.go
# github.com/jhaals/yopass/pkg/yopass
jhaals/yopass/pkg/yopass/yopass.go:50:19: multiple-value uuid.NewV4() in single-value context
```

Info:

```# go version
go version go1.10.4 **linux/amd64**

# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build556093694=/tmp/go-build -gno-record-gcc-switches"

```

**Comment by jhaals** [comment]
Hi @Pandemic21, are you sure you are using go modules? That should make sure you get the correct versions of dependencies. You can also run yopass via the container if you don't want to mess with building it youself.

**Comment by Pandemic21** [comment]
Nope @jhaals, I'm not sure. I'm not too familiar with Go and probably messed something up myself, I'm just not sure what. 

I'll try again and see if it'll work this time. I'm not sure how much value you'd get out of it, but if you get a chance I know at least I would definitely appreciate some directions with step-by-step commands on how to get self-host it. Like I said though, not sure if it's worth the time to make that documentation with only one guy asking for it.

**Comment by jhaals** [comment]
I noticed that your go version is probably the problem, upgrade to the latest(1.14) one which should use go modules by default without having to specify environment variables to build. The docker file is meant for self hosting but if you want to build it yourself from scratch you can just build the docker image locally on you manchine or use the container as build host and copy the binary to your machine afterwards.
