### ISSUE TITLE
Feature Request: Add a "Copy to clipboard" button when viewing a decrypted message

### ISSUE THREAD

**Issue by deadlydog** [jhaals/yopass#442]
Currently you have to manually select and copy the text, which is easy enough to do. However, it's also easy to miss some of the text by accident and only copy a portion of the text. Because the messages expire, and may be configured for "One-time download" so they can only be viewed once, it would be helpful to have a "Copy to clipboard" button on the Decrypted Message page to ensure that all of the text gets copied correctly.

**Comment by jhaals** [comment]
Thanks for the suggestion, I will take a stab at this once I get some extra cycles 👍

**Comment by jhaals** [comment]
Implemented in #443
