### ISSUE TITLE
Bare metal deployment returns 404

### ISSUE THREAD

**Issue by wsandin** [jhaals/yopass#449]
I'm attempting to setup yopass compiled from source based on the latest tag, listening to localhost with a reverse proxy in front. However I can't reach the yopass instance. What may I be missing?

Many thanks for a great piece of software that served me well on many occasions.

```
# ps uaxww | grep -E 'yopass|redis'
redis    18838  0.1  0.0  51444  2376 ?        Ssl  23:12   0:00 /usr/bin/redis-server 127.0.0.1:6379
yopass   19471  0.0  0.2 313464  7728 ?        Ssl  23:13   0:00 /usr/bin/yopass serve --address 127.0.0.1 --port 8080 --database redis


# curl -X GET http://localhost:8080
404 page not found
# curl -X GET http://localhost:8080/yopass
404 page not found
```

**Comment by jhaals** [comment]
Hi, thanks for the kind words. 
My guess is that you haven’t built the website which the app expects to serve from the folder named public.
