### ISSUE TITLE
Feature request: password for redis connection

### ISSUE THREAD

**Issue by Strange-Account** [jhaals/yopass#457]
Hi,

please support a password for the redis connection, so I can use a redis installation outside the yopass installation (eg. from environment variable for k8s). 

THX

**Comment by jhaals** [comment]
Hi, I believe password are already supported since yopass uses https://pkg.go.dev/github.com/go-redis/redis/v8?tab=doc#ParseURL to parse the connection url.  

```
opt, err := redis.ParseURL("redis://:qwerty@localhost:6379/1")
if err != nil {
	panic(err)
}
fmt.Println("addr is", opt.Addr)
fmt.Println("db is", opt.DB)
fmt.Println("password is", opt.Password)
```
output

```
addr is localhost:6379
db is 1
password is qwerty
```
