### ISSUE TITLE
Failed To Fetch

### ISSUE THREAD

**Issue by onabison** [jhaals/yopass#459]
Hi,

I have just started using this app. Its running on my EKS cluster. The containers are running and are healthy. It worked for a new days like a charm, but now, when I try to Encrypt a message it just returns "Failed to fetch".
![image](https://user-images.githubusercontent.com/35974508/82078887-c2761200-9696-11ea-9899-7d49c378c7a7.png)

Looking at the container logs I don't see anything other than ALB health checks:

10.5.x.x - - [15/May/2020:17:19:27 +0000] "GET / HTTP/1.1" 200 2609
10.5.x.x - - [15/May/2020:17:19:27 +0000] "GET / HTTP/1.1" 200 2609

I tried to kill the pod and a new one created but exact same behavior. 

Anyone experienced this?

**Comment by salincakli** [comment]
Yes, I can confirm this behaviour!

**Comment by onabison** [comment]
I deleted everything and started from scratch and it works now. I don't know exactly that the issue what. so I'm sorry for the next person who bumps into this as I did not find the root cause. I just re-build and it works.
