### ISSUE TITLE
Cannot find package "github.com/go-redis/redis/v7"

### ISSUE THREAD

**Issue by wsandin** [jhaals/yopass#474]
```
: ~/go/src/github.com/jhaals/yopass/cmd/yopass git:(master) $ /usr/local/go/bin/go get
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring ../../go.mod;
	see 'go help modules'
package github.com/go-redis/redis/v7: cannot find package "github.com/go-redis/redis/v7" in any of:
	/usr/local/go/src/github.com/go-redis/redis/v7 (from $GOROOT)
	/home/ws/go/src/github.com/go-redis/redis/v7 (from $GOPATH)
```

**Comment by jhaals** [comment]
Hi @wsandin, 
I looked at the redis package and it appears it should be imported with the version prefix.
See https://github.com/go-redis/redis/tree/v7#installation for more information.
I have you problems resolving the dependencies in my tests/build. Make sure you have an updated go version.

**Comment by wsandin** [comment]
Thanks, that was indeed right - it worked just fine after upgrading to 1.14.x.
