### ISSUE TITLE
Failed to Fetch

### ISSUE THREAD

**Issue by onabison** [jhaals/yopass#530]
I had to move the app to my new EKS cluster. Once I moved it, the app never worked as it used to. I would take a while to load and once it does and I try to translate a message it just says "Failed to Fetch". I tried updating the forked branch but that did not seem to make a difference. I can see the pod is running and the logs are only showing heath checks from the ALB, nothing else.

**Comment by onabison** [comment]
Seems like I posted the exact issue a few months back. Back then re-building the app fixed it. Not this time.

**Comment by jhaals** [comment]
I'm sorry but this is too little information for me to help you troubleshoot this issue. Sounds like there's issues with communication between frontend and backend. Please use a docker hub version. The master branch might not be in running condition but its usually are.

**Comment by onabison** [comment]
I resolved it. I was not related to code.

*Regards,*
*Nave Koren*
*818-314-5784*
