### ISSUE TITLE
Prometheus support

### ISSUE THREAD

**Issue by grobie** [jhaals/yopass#536]
Hey @jhaals,

first of all, thanks so much for yopass, we're big fan here at SoundCloud! It's our favorite tool to quickly share some credentials with others.

We wonder if you were to accept a submission to add Prometheus monitoring to yopass, to track number of requests and errors? I saw that the prometheus client library is already in the list of dependencies. So we'd only need to load the library, add one metric, and expose the `/metrics` handler. https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#InstrumentHandlerDuration

Cheers!

**Comment by jhaals** [comment]
Hi @grobie!

Thanks a lot for the kind words! I'm so glad to hear that SoundCloud is using Yopass.
Adding prometheus metrics would be a great addition! Feel free to submit a PR and if other things could be improved please let me know or submit it in a separate PR 👍
