### ISSUE TITLE
Support keyboard shortcuts

### ISSUE THREAD

**Issue by grobie** [jhaals/yopass#579]
When loading the yopass website the input field is immediately in focus. I'd love to send off the form after pasting/entering some plaintext by keyboard shortcut. At least under Linux based Firefox 80.0 the common ctrl+enter combination is not recognized to submit the form. Maybe it would even be possible to be able to copy the one-click link  with ctrl+c or some other combination on the next page?

I don't really have any experience with Typescript/Javascript to add that quickly myself.

**Comment by jhaals** [comment]
This sound like a good idea! I'm not sure one click copy can be achieved with keyboard shortcuts from a website but it's worth researching 👍
