### ISSUE TITLE
Feature Request: Reply to note | Create Email Service

### ISSUE THREAD

**Issue by trymeouteh** [jhaals/yopass#591]
Yopasse is essentially like ProtonMail encrypted emails for non-Protonmail users except your unable to reply to the message. Please add a setting to allow users to reply to an encrypted message. This is how I can see this being implemented.

- An optional setting where the sender enters their email address into the message and when the message revives any replies, it will send an email to that email address notifying them sender the recover has read and replied.

- Add a reply button were you can type a reply message box and click submit, once that is done it will show the link to the encrypted message that can easily be copied and the user can send this link back to the person they are communicating with via email.

https://protonmail.com/support/knowledge-base/can-outside-users-respond-to-encrypted-messages/

**Comment by jhaals** [comment]
Sorry but yopass is created for one way transactions and I have no plans of implementing this feature. Checkout keybase.io if you want encrypted messages or Signal.

**Comment by trymeouteh** [comment]
I understand. I see yopasse can be a good alternative to services that protonmail and tutanota offers were you can send encrypted emails to others without PGP which is simply a link to a webpage which is encrypted and requires a password to unlock and read.
