### ISSUE TITLE
Default Options Changed

### ISSUE THREAD

**Issue by trymeouteh** [jhaals/yopass#594]
Please consider changing the default options to be the following...

The encrypted message will be deleted automatically after = One Week (or 28 days)
One-time download = off
Generate decryption key = off

I feel this will be a better default settings. If someone wants to have a generated decryption key, they will be forced to select the option since the user will not fill out the decryption key fiend, no accidental one-time download expiry messages and messages will last awhile.

**Comment by jhaals** [comment]
Thanks for the suggestion but I want the defaults to be as strict as possible. You can easily clone this repository and tweak these settings for your installation.

**Comment by trymeouteh** [comment]
Is it easy to create a yopasse instance on my own hosting and domain and tweak the settings I mentioned above to my liking without having to fork this project?
