### ISSUE TITLE
Release 10.0.0

### ISSUE THREAD

**Issue by grobie** [jhaals/yopass#614]
Hey @jhaals,

I'd like to make it easy for some friends on Arch to install the new CLI by updating https://aur.archlinux.org/packages/yopass/. I also thought about publishing it on homebrew, but without access to a Mac I need to see if I can get it to work. Any chance a new release could be published? Anything you'd like to see done before doing so?

**Comment by jhaals** [comment]
Hi @grobie, 

I don't think there's anything preventing a 10.0.0 release at this point :) 
I also thought of homebrew, I have a Mac but haven't got to creating a tap or formula yet.

Anyway release incoming!

**Comment by grobie** [comment]
Thanks a lot! Arch package install 10.0.0 now: https://aur.archlinux.org/packages/yopass/ (added a new split package https://aur.archlinux.org/packages/yopass-server/ as well)

**Comment by jhaals** [comment]
Awesome stuff! 🙌
