### ISSUE TITLE
Suggestion: Add toggle to prevent One-time download from being unchecked

### ISSUE THREAD

**Issue by pjmpsu** [jhaals/yopass#624]
We would like to setup yopass for users to share secrets but we do not want them to have the option to un-check the "One-time download" option when creating a secret.

**Comment by aba-rechsteiner** [comment]
+1

**Comment by aba-weissenberger** [comment]
Yes, that would be a nice option.

**Comment by SporkAscendant** [comment]
This feature would be helpful for me as well. Thanks!

**Comment by jhaals** [comment]
This is hard to do client side since the website is static. The option can however be added to the server as a flag so that non onetime secrets will be rejected.

**Comment by pjmpsu** [comment]
That would work for me.

**Comment by aba-weissenberger** [comment]
+1

**Comment by jhaals** [comment]
fixed by #664
