### ISSUE TITLE
Add CONTRIBUTING, Issue Template and Pull Request Template

### ISSUE THREAD

**Issue by jesperorb** [jhaals/yopass#641]
Could be a good idea to add some info on how to contribute or what is expected to be present in a pull request that is being opened. I suggest adding a `CONTRIBUTING.MD`, `CODE_OF_CONDUCT.md`, _A PR-template_ and an _Issue Template_ to lower the threshold for contributing. Doesn't have to be fleshed out just some pointers.

* [Setting guidelines for repository contributors](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors)
* [Using templates to encourage useful issues and pull requests](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests)

**Comment by jhaals** [comment]
Yeah this has been on my mind to add. Thanks for the reminder, I will leave this as a todo and address this after I've reviewed some prior art.

**Comment by jhaals** [comment]
@jesperorb I've added a CONTRIBUTING.md file. PTAL and if you are happy please close this ticket, otherwise send a PR :)

**Comment by jesperorb** [comment]
Nice :+1:

> Fantastic! Issues tagged with **enchantment** are ready to be picked up. If you have other ideas on how to improve please reach out in an issue :)

You are a true role player
