### ISSUE TITLE
Custom CSS and page design: Howto?

### ISSUE THREAD

**Issue by essdeeay** [jhaals/yopass#658]
Hello - and please just remove this request if it's not in the right place. Firstly, a big thank you for Yopass...

Is there any indication of how to customise the CSS and page design for Yopass when running in docker, using docker-compose to build?

**Comment by jhaals** [comment]
You can customise as much as you'd like and then run yarn build and make sure that the public folder is replaced with your custom version in the end. Either build a new docker container or simply volume mount the new public folder into the yopass container.

**Comment by mofolo** [comment]
Hate to re-open an old issue @jhaals. 
I've worked through the docker-composer and tried to find which volume is actually calling the `public` directory and where!? 
Could you help me understand, do I need commit my own docker image on `jhaals/yopass` and what's the directory where these source files are stored within this image?

Thanks!

**Comment by mofolo** [comment]
@jhaals - Ignore me.
I built my own docker container by cloning the git then running `docker build .` after modifying the website source and updated the docker-composer file to the image that I created and it worked flawlessly. Thanks for your efforts here!
