### ISSUE TITLE
Add a "Retry with another password" feature to the UI

### ISSUE THREAD

**Issue by jeyred** [jhaals/yopass#672]
As a user of yopass I expect that I am able to correct a wrongly entered password.

In fact a one time secret is deleted on the first wrong attempt and the UI does not offer me an option to try another password.

Background: I got a password by snail mail. With the font used to print the password It was hard to distinguish the letters l (lower case L) and I (upper case I) and obviously I did it wrong on the first attempt. After that I tried all possible combinations (only 4 in my case): no luck.

Now I analyzed this in depth and tried yopass myself with a test secret and saw this behavior. I had a chance of 25% and lost... ;)

So my request is to add a "retry with another password" feature in the UI.

I think for security reasons the server deletes a one time secret on the first read without any knowledge of the password given to the client (and in consequence there is no second request to delete a secret). A solution could be that the client stores the ciphertext in memory as long as an incorrect password was given. This way it is at least possible to correct the password in the same session. It is Ok that it's not possible to open a second session for more password tries.

**Comment by jhaals** [comment]
I think it's fair that you get to retry the password in your session. I'll leave this ticket to be implemented by me or some lovely contributor down the line 👍
