### ISSUE TITLE
To add Sentinel as option for Redis installation.  

### ISSUE THREAD

**Issue by MaxDukov** [jhaals/yopass#734]
Hey.
  first of all - thanks a lot for your great project!
We use yopass for a few days in Kubernetes and one of the disadvantages of standard installation is Memcache stateless. It lost all data for each pod restart/migration. So we change Memcache to Redis. It has persistence as an option, but the next step for me is to use Redis in clusters mode. So I tried Sentinel - and found that yopass unable to use it. 
   I'm ready to add Sentinel support myself and make a pull request if it's ok.

**Comment by jhaals** [comment]
Hi Max and thank you for the kind words!
I'm a hesitant to add new databases as it will be problematic for me to provide support for several providers. The database interface is very simple so I'd suggest you run a custom build with your database of choice.

**Comment by MaxDukov** [comment]
Sentinel is not a new database, it's a method to make Redis clustered. Ok, I will make a fork, it's quite important for me.
