### ISSUE TITLE
Secrets opened by third apps

### ISSUE THREAD

**Issue by tntteam** [jhaals/yopass#741]
Hello there !
Thank you for your application, very neat.
We have an issue when sharing links :
If I share a link with one click link, the secret may be opened by the communication program (url preview or other stuff like that, even local computer antivirus may open secret).

We thought to avoid this would be to share short link and decryption key separately.
The problem is when we share short link using our rocket.chat, it opens the link and I think yopass binds the secret to our rocket.chat server because it is not possible to open the password later, even if our rocket.chat didn't fully open the secret because it did open the short link (and hence doesn't know about decryption key).

I checked using private navigation : once you open the short link (without decryption key) from a specific IP, and don't enter the decryption key, then you can't open it at all from any other IP with the decryption key.

I think there could be 2 options to counter this : 

- Add a "I want to open and destroy the secret" confirm warning (would also prevent the problem when sharing one click link)
- Do not bind a secret to the first IP who opened it, unless it entered the decryption key

Sorry for my poor english and have a nice day :)

**Comment by jhaals** [comment]
Hi @tntteam and thanks for reporting.

This was a problem way back when yopass was server side. However it has not been a problem since the encryption moved to being client side because the preview never evaluated javascript. Sounds like this is no longer the case for some preview services... 

Would be nice to not have extra options or user input required. Perhaps some timer before doing the actual fetch.

**Comment by tntteam** [comment]
Hello !
I think I failed to explain properly the issue :)

You open shortlink (without the decryption key) on computer A
You don't enter decryption key
You open shortlink (without the decryption key) on computer B
You do enter the decryption key : "the secret does not exist"

So I think there is something server side here.

Or I am missing something ?

**Comment by jhaals** [comment]
Thanks for the clarification!

The current implementation fetches directly based on the key. I guess it could be updated to always change a password prompt and download after the user press submit.

**Comment by BloodyFrag** [comment]
Great app! But I would also like to send "One-Click Link" through third apps. Can you please add the "View Secret" button on the "One-Click Link" pages, like OneTimeSecret?
