### ISSUE TITLE
Question regarding using of a API

### ISSUE THREAD

**Issue by pkruk** [jhaals/yopass#749]
Hi,

I would like to ask, how to use a API. 

I want to generate links to my local instances of yopass from a script and I'm testing it at now with using postman and pgp:

```
echo foo | gpg --symmetric --armor
-----BEGIN PGP MESSAGE-----

jA0EBwMCFK+YEOUfr0rj0jkBX8yZ8qLWEeedAZDi1pAF6otxfQAG1YF8kNI659Tp
Tq8RehY86OxLJoNS1yZnGW2xf0Od7Nd1DrA=
=kdrH
-----END PGP MESSAGE-----
```

Send POST http request with a body:

```
{
    "Expiration": 3600,
    "message": "-----BEGIN PGP MESSAGE-----jA0EBwMCFK+YEOUfr0rj0jkBX8yZ8qLWEeedAZDi1pAF6otxfQAG1YF8kNI659TpTq8RehY86OxLJoNS1yZnGW2xf0Od7Nd1DrA==kdrH-----END PGP MESSAGE-----"
}
```
Getting the response: {"message":"08a3f736-f7ea-4926-86f2-764540c682b0"}

Going to the url: 

https://MY_FANCY_URL/#/s/08a3f736-f7ea-4926-86f2-764540c682b0

Passing a secret and then I got a:

```
Secret does not exist

It might be caused by any of these reasons.
```

What I'm doing wrong? my pgp require some extra args? Will be glad for any tip :)

**Comment by jhaals** [comment]
Hi @pkruk!

I have not had had the time to dig into this yet but it should definitely work

**Comment by jhaals** [comment]
Hi

I just confirmed that this worked without issues with line breaks

```
curl -X POST -d "{\"message\": \"-----BEGIN PGP MESSAGE-----\n\njA0EBwMCbc3gUNhLJ8Ls0jkBp4o+KNEhqaD4wTY2iG/D1BU3MOhmNuWK4306eYeg\npW9b00ias3O1o0h7aSLQfSfhpOts7L8Q2jQ=\n=ujbv\n-----END PGP MESSAGE-----\", \"expiration\": 3600}" https://example.api.com/secret
```

password 123

**Comment by pkruk** [comment]
Yes, you're right adding '\n' solves my problems :) Thanks :)!
