### ISSUE TITLE
API call by curl 

### ISSUE THREAD

**Issue by rafalsc** [jhaals/yopass#776]
Hello,

I installed yopass bin. and when I use that all is fine with my yopass server.

`echo test | yopass
https://yopass.test-server.org/#/s/ffb852cd-f187-4013-8157-2bafcf86fedf/Qsn8fujtP7Uxj-smlYO4K7`

I would like to have the same function by calling my server by curl. I have some automatisation and only one option to use it, I have by curl. I tried do it by:
`curl --header "Content-Type: application/json" --request POST --data '{"secret":"secret","Expiration":3600,"key":"test1","decrypt":"test2"}' https://yopass.test-server.org/secret`

I got that message after:
`{"message":"eb8e5125-7ff2-40fe-8dd1-a209ac2c1fbf"}%`

I tried many options to copy that message to that URL: `https://yopass.test-server.org/#/s/eb8e5125-7ff2-40fe-8dd1-a209ac2c1fbf/test2`, but no luck. 

Could you help me with that? I will be very thankfull.

Best,
Rafal

**Comment by jhaals** [comment]
Hi Rafael, you need to handle the encryption/descryption yourself if you're not using the yopass cli. 
There's a curl example in #749. 

Good luck!
