### ISSUE TITLE
Connect to container

### ISSUE THREAD

**Issue by mickbar37** [jhaals/yopass#777]
Hello,
i can't connect to the container jhaals/yopass. 
how can i connect for modify logo or adapt the web page for example ?  
the classic commande like exec with bash doesn't work.

thanks :)

**Comment by jhaals** [comment]
Hi, I can't really you connect to the container as I don't know anything about the setup. 
But you should be able to reach it on http://localhost:1337
if you start both memcached and yopass
```
docker run --name memcached_yopass -d memcached
docker run -p 1337:1337 --link memcached_yopass:memcache -d jhaals/yopass --memcached=memcache:11211
```

You have to rebuild container Dockerfile yourself if you want to modify the website. You can just make the modifications locally and then run docker build.

The container does not have bash or sh installed.
