### ISSUE TITLE
Hashicorp HCL Package Dependency Correction

### ISSUE THREAD

**Issue by unstatusthequo** [jhaals/yopass#778]
Just noticed in the compile instructions, when executing the `go get... && go install...`, the error returned suggests  that the hashicorp HCL printer package cannot be found.  Looking manually at the Hashicorp repo, it seems the hcl directory is no longer there, superseded HCLv2, so the compiling of yopass from command line fails. I have go 15.2 installed. 

the go.sum file in this repo references: 

```
github.com/hashicorp/hcl v1.0.0 h1:0Anlzjpi4vEasTeNFn2mLJgTSwt0+6sfsiTG8qcWGx4=
github.com/hashicorp/hcl v1.0.0/go.mod h1:E5yfLk+7swimpb2L/Alb/PJmXilQ/rhwaUYs4T20WEQ=
```

**Comment by jhaals** [comment]
Thanks for reporting @unstatusthequo 

HCL is a dependency of viper which yopass is using.  This is the explanation to the error you're seeing. https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md#cannot-find-package

The installation will pass if run go with the `GO111MODULE=on` environment variable set.
I will update the readme with
```export GO111MODULE=on && go get github.com/jhaals/yopass/cmd/yopass && go install github.com/jhaals/yopass/cmd/yopass```

**Comment by unstatusthequo** [comment]
On Go 1.16, I had to add @latest to the end of each of the go commands in that line, resulting in this, which worked great: 

`GO111MODULE=on && go get github.com/jhaals/yopass/cmd/yopass && go install github.com/jhaals/yopass/cmd/yopass@latest`
