### ISSUE TITLE
Cannot see or barely see the first letter

### ISSUE THREAD

**Issue by alex1atd** [jhaals/yopass#797]
Hello,

We found a bug when trying to write a secret message. Here are some examples for the same issue, more exactly:

**1.** If i write the word "yopass" we barely see the first letter.
![image](https://user-images.githubusercontent.com/69236977/109779945-2a3e1f00-7c0f-11eb-947a-485af73c525e.png)

**2.** If i write the word "jenkins" we cannot see the first letter. 
![image](https://user-images.githubusercontent.com/69236977/109780063-4b067480-7c0f-11eb-88a6-597ad6df1e3c.png)

**3.** In this printscreen, we cannot see the vertical bar "|"
![image](https://user-images.githubusercontent.com/69236977/109781553-b1d85d80-7c10-11eb-9833-4ff34d275b26.png)

**4.** In this printscreen, i spaced once the vertical bar "|" and this is why we can see it;
![image](https://user-images.githubusercontent.com/69236977/109780582-d1bb5180-7c0f-11eb-88de-dfd27a5769a4.png)

My suggestion is to move the vertical bar "|" a little bit to the right in order to see also the first word.

The test was made using Firefox:
![image](https://user-images.githubusercontent.com/69236977/109780324-9456c400-7c0f-11eb-8535-e23f6dfcb05e.png)

Please let me know if any other information is needed.

Thank you.
Alexandru

**Comment by jhaals** [comment]
Hi Alexandru and thanks for reporting this problem!
Just to clarify do you see this problem if you visit https://yopass.se or is it only a problem on your local installation?

**Comment by alex1atd** [comment]
Hi Jhaals,

The problem is only on my local installation.

Thank you.
Alexandru

**Comment by jhaals** [comment]
Okay that's good news, I'll make a new release tomorrow which will include
some ui fixes. You could also just run the latest if you want.
