### ISSUE TITLE
Adjust CLI URL generation

### ISSUE THREAD

**Issue by grobie** [jhaals/yopass#799]
Thanks a lot for another release! The [AUR package](https://aur.archlinux.org/packages/yopass/) has been updated :-) 

It appears you consolidated the URL paths, which is great! The CLI will need to be updated to reflect this as well. I'm more than happy to take care of that over the weekend.

**Comment by grobie** [comment]
I can't assign myself to this ticket, so consider myself assigned :wink:

**Comment by jhaals** [comment]
Thanks for looking at this @grobie 👍
