### ISSUE TITLE
[bug] "TypeError: navigator.serviceWorker is undefined"

### ISSUE THREAD

**Issue by grobie** [jhaals/yopass#808]
Opening a link generated by yopass 11.1.0 in Firefox incognito mode will trigger `TypeError: navigator.serviceWorker is undefined`.

It's triggered by this line: https://github.com/jhaals/yopass/blob/7b7a45cb9f82890188dfe916d98e99dbfc9b9012/website/src/App.tsx#L13

![Screenshot from 2021-03-08 09-51-50](https://user-images.githubusercontent.com/3432/110297592-f8a0cb80-7ff3-11eb-9ae2-fb04d43bd503.png)
URL: https://yopass.se/#/s/a4e4f488-fc61-4215-857a-512557dd8418

**Comment by jhaals** [comment]
ah, there's no serviceWorker in private tabs, I'll fix it.

**Comment by jhaals** [comment]
Fixed by https://github.com/jhaals/yopass/commit/b327957873d9e93936f29959e026f632166eda2a and released in 11.1.1, thanks for reporting!
