### ISSUE TITLE
OpenAPI Spec for backend

### ISSUE THREAD

**Issue by freisenhauer** [jhaals/yopass#810]
Hello 👋 

For one of our use cases we just need the backend of yopass and we are generating our api clients from OpenAPI Specs .. therefore, we wrote one for the yopass backend. If its somehow helpful for you, I would like to contribute it. 

Greetings
Frederic

**Comment by jhaals** [comment]
Hi Frederic,
I have not given OpenAPI Specs much thought given how simple the API is currently. I am however planning on new features that might change the API so it might be a good idea to have the spec. Feel free to submit a PR so that I can have a look!

**Comment by jhaals** [comment]
Closing for now, reopen if need be.
