### ISSUE TITLE
Improved self-hosting install instructions?

### ISSUE THREAD

**Issue by strider72** [jhaals/yopass#820]
I'm fairly tech savvy, but I guess I need a bit more hand-holding RE installing this on my own site.  The limited directions are written as though I already know how to do it(?)

**Comment by flobeier** [comment]
@strider72 I added a new Docker Compose file that should simplify getting a whole setup with TLS encryption running. Please have a look at the updated README file.

**Comment by jhaals** [comment]
I'm going to close this since the latest contribution by @flobeier greatly improves the install instructions
