### ISSUE TITLE
Update node-gyp to remove dependency on Python 2

### ISSUE THREAD

**Issue by bitfehler** [jhaals/yopass#831]
Hi there!

First of all, thanks a lot for all this, we are big fans of Yopass! We deploy our own instance and recently ran into problems because we tried to get rid of Python 2 on the underlying system. The issue seems to be that node-gyp is locked to version 3.8.0, which does not yet have support for Python 3 (see https://github.com/nodejs/node-gyp/issues/193).

Python 2 is basically obsolete by now, so getting rid of this dependency would be really great.

Unfortunately I am not very versed with the whole node ecosystem tooling, so providing a PR would take me quite some effort. If someone with more skills on that front could maybe jump in that would be much appreciated. However, if so desired, I can also try my luck at this.

**Comment by jhaals** [comment]
Hi @bitfehler and thanks for the kind words, really appreciate hearing this!

Glad you pointed this out, it turns out this was part of node-sass which isn't used anymore so I removed it entirely :)
