### ISSUE TITLE
Support for larger file upload

### ISSUE THREAD

**Issue by jonny-wg2** [jhaals/yopass#845]
### Feature Idea:
It would be great if there was an argument flag we can set for the max size of file upload, e.g. 1mb

### Background:
We run our own instance of yopass and we all love it. I have seen many developers, however, get frustrated when trying to upload a file - as the length is too small.

From memcache 1.4.2 we [can configure](https://github.com/memcached/memcached/wiki/ReleaseNotes142#configurable-maximum-item-size) the max file upload length. I have tried this - but believe there is something still stopping this upload in yopass backend.

**Comment by vonNiklasson** [comment]
[Could it be this line](https://github.com/jhaals/yopass/blob/master/website/src/createSecret/Upload.tsx#L20)?

```
const Upload = () => {
  const maxSize = 1024 * 500;
  ...
```

**Comment by jonny-wg2** [comment]
@vonNiklasson I actually managed to get it working locally by removing this check. I was able to get uploads of around 500kb which is perfect for small files.

https://github.com/jhaals/yopass/blob/fb3e0f9e974fb891e4d944f9f7e49a97430eba61/pkg/server/server.go#L58-L61

**Comment by jhaals** [comment]
Increasing the `max-length` in yopass-server is the way to get larger uploads as @jonny-wg2 so kindly suggests. There's a hard limit on memcache for file uploads which is 1mb. I'm open to bumping the max size in the UI to allow for the maximum upload if people are interested in contributing that ;) I gave an explanation to the different limits in this issue #1007.

**Comment by DRogueRonin** [comment]
I tried to upload a file with around 800kb in size and I am getting the "translations:upload.fileTooLarge" error feedback from the UI. (I increased memcached and the server max-length)

If I assume correctly then it's really just this line
https://github.com/jhaals/yopass/blob/master/website/src/createSecret/Upload.tsx#L20
that needs to be adjusted.

Not taking into account the adjustments for an additional config parameter.

I never wrote a line of go, but I could try to implement that.

**Comment by DRogueRonin** [comment]
A point of discussion would be where to add that configuration option.

Since the UI is prebuilt and not interacting with the `yopass-server` command  
and for UX reasons  
it should be an additional option for the server command,
like `--max-file-size` or something.

The UI then needs to get that value from the server when rendering the Upload view.

Does that sound acceptable?
