### ISSUE TITLE
Stop Grammarly sending your secrets to their servers

### ISSUE THREAD

**Issue by justin-atkins-signifo** [jhaals/yopass#868]
Users with the Grammarly extension will have the secret field contents transmitted to Grammarly servers. To prevent this add the attribute data-gramm="false" to the secret textarea.

See for reference: https://stackoverflow.com/questions/37444906/how-to-stop-extensions-add-ons-like-grammarly-on-contenteditable-editors

**Comment by jhaals** [comment]
Closed by #893
