### ISSUE TITLE
Stuck on "Fetching from database, please hold".

### ISSUE THREAD

**Issue by david-wg2** [jhaals/yopass#883]
First of all, thank you for a great project @jhaals :)

<img width="648" alt="Screen Shot 2021-05-07 at 12 00 33" src="https://user-images.githubusercontent.com/36410074/117433573-e972c700-af2b-11eb-9604-d633917b6f2f.png">

At my company, we've recently had some issues where we get stuck on this screen if the person consuming the link has used an older version of a Yopass before (can be fixed by clearing cookies).

Today, I experienced something new. I was trying to send a link to one of our partners, and he couldn't get the page to load no matter what he did. Eventually, we figured out that the machine that created the link needed its cookies cleared for the link to work properly.

Proposed short term fix: Please include a hint about clearing cookies, both for the browser supplying and consuming the link.
Proposed long term fix: Prevent this from happening at all, don't involve the browser state in creating/consuming the links.

**Comment by david-wg2** [comment]
> I don't think this is cookie related as yopass does not use them at all, however this sounds like an issue with a registered serviceWorker that tries use the browser cache.

That sounds plausible, I think the "Clear cookies" option gets rid of all client state (cookies, service workers, local storage).

> This should be fixed by a browser refresh for a yopass 11.1.1 and above.

Just so we're on the same page, this is what happened:

* I created a link on my desktop computer and sent it to our partner
* Our partner tried opening it, and got the `Fetching from database, please hold` message
* Our partner tried multiple different browsers and devices, but could get the `Fetching from database, please hold` message
* I finally tried the link on my laptop, and also got `Fetching from database, please hold`
* I cleared the cookies on my desktop computer, which enabled it to create "uncorrupted" links again

Whether it's solved by deleting cookies or simply refreshing is secondary IMO. It should never be possible to created "corrupted" links because of the browser state.

Since this is unintuitive behavior I think it would be very helpful to add a hint in the `Fetching from database, please hold` screen. Ideally it should be possible to determine that no fetching will take place, and just show an error message instead.

**Comment by jhaals** [comment]
Thanks for the clarification.
Hearing the issue occurred in several browser make me believe this was not related to service workers or any caching. Please check if any request is sent to the backend using developer tools or if this is simply some bug in the UI code that gets triggered. I'm struggling to reproduce this myself. Which version of Yopass are you using?

**Comment by david-wg2** [comment]
I see that encryption/decryption is done by the client rather than by the server. Is this for performance, or some other reason? I guess that would explain how you could end up with clients producing corrupted links. What do you think about a config-option to do this on the server-side instead?

**Comment by jhaals** [comment]
I realise I should have replied a lot earlier but this has simply got lost.
The encryption is done client side which means no sensitive information like the decryption key or the unencrypted content is sent over the wire. All is done locally, I have no plans on making this a server side operation for those reasons. I really hope you managed to solve the problem by now, otherwise feel free to reopen this already stale issue. Stay safe!
