### ISSUE TITLE
Feature Request: Ability to Disable a Yopass Link immediately

### ISSUE THREAD

**Issue by Keetmalin** [jhaals/yopass#918]
Currently, we can generate links for a certain time period. But sometimes, we have the requirement of disabling it after issuing the link.

**Comment by jhaals** [comment]
I would probably recommend that you issue one-time secrets for each user as invalidation of the secret would simply be a visit away. Exposing an option to delete a non onetime secret shared with multiple people would make it possible for anyone with the link to delete it for the rest as there's no authentication mechanism except for the decryption key.

**Comment by Keetmalin** [comment]
Hi @jhaals, yes that makes sense. Even if the secret is exposed once, the best option would be to regenerate the secrets from our end. I will close this issue.
