### ISSUE TITLE
Improve internationalization

### ISSUE THREAD

**Issue by rbicker** [jhaals/yopass#930]
Hi

I would like to contribute to yopass by improving the internationalization of the web frontend. This is what I have in mind:
- I would like to make the i18next fallback language configurable by introducing a new env variable (something like REACT_APP_FALLBACK_LANGUAGE, English by default). This way, if you build and host your own local yopass, it can default to your local language.
- I would like to enable browser language detection by adding the i18next-browser-languagedetector plugin (https://www.i18next.com/principles/plugins) to the frontend. This way, yopass can be multilingual! Contributors could provide language files. If languages are missing or existing language files have missing keys, it would fall back to the fallback language specified at build time (so you would not have to wait for contributors to update language files when updating the frontend).
- Currently, the frontend not only provides English strings in the json language file but also as fallbacks in the keys. This is not necessary, also it increases the work to maintain the translations because you have to adjust all the strings twice on changes. It is also not recommended by i18n: https://www.i18next.com/principles/fallback#key-not-found. I would like to rename the keys and to give them a unique name in the frontend and in the language json file.

Please let me know if you agree with my suggestions. If so, I will create a pull request.

Thanks!

**Comment by jhaals** [comment]
Hi @rbicker, thanks for starting by raising an issue about this 👍 
I have been on vacation until recently so I haven't kept up with issues.

I'm open to improving internalization in yopass, however I'm very hesitant to accept language contributions as they tend to go out of date very quickly when something changes in the UI, I had requests to add 5ish languages to yopass so far and it would be terrible for me to have to reach out to those users for translation updates when a new version is released that changes the layout or wording.
With that said, I'm open to having some way of overriding or a workflow with instructions for those who which to run multiple languages with their own translations but I'm not willing to ship secondary languages in yopass by default if that makes sense.

Thanks again for reaching out and I hope we can work something out.

**Comment by rbicker** [comment]
Hi @jhaals 

Thanks for your feedback! Not accepting language contributions because it would complicate / slow down your release process makes perfect sense! 

We think the main issue is that it is currently not that easy to maintain own translations because of some restrictions the current implementation brings. So this is why we would like to create the pull request. For your workflow, the only change would be that you are not having the complete text fragments in your source code plus in the json file. The source code will include a key (like "introduction") and the json will include the text fragment for the key (like "hello world"). So people can create their translation in json (`{ "introduction": "Hallo Welt" }`). If you change the wording of the introduction (to "Hello World!!!"), the translation would still work. If you create a new text fragment (= a new key) in a release, the translation would not be found, so a fallback to REACT_APP_FALLBACK_LANGUAGE (English by default) would happen. 

Maybe the way to solve language contributions could be having language contributions in different repositories, not maintained by you? So you could just link to these repositories within your README (including a statement that you are not the one maintaining / updating these contributions). Maybe we can work something out that works for you. Either way, the first step would be doing the improvements stated above.

**Comment by jhaals** [comment]
Hi @rbicker,

Thanks for taking on this task 👍 This sounds good to me, I'll review your PR as soon as I have some time to spare.

**Comment by rbicker** [comment]
Hi @jhaals, that is great, thank you very much for your time!
