### ISSUE TITLE
docker-compose results in "exec format error"

### ISSUE THREAD

**Issue by Mellbourn** [jhaals/yopass#976]
When I try to use either of the `docker-compose.yml` files, I immediately get the following error in the `yopass` container:
```
standard_init_linux.go:228: exec user process caused: exec format error
```

I'm running docker on a Raspberry Pi 4.

**Comment by sheeeng** [comment]
Raspberry Pi 4 has a different machine architecture, namely [ARM v8](https://www.raspberrypi.org/products/raspberry-pi-4-model-b/specifications/).
https://github.com/edgedb/edgedb-docker/issues/2#issuecomment-516618358

**Comment by jhaals** [comment]
As sheeeng kindly replied the binary is not built for arm. I have no plans on supporting that architecture at this point in time but you can compile the server for arm, see Golang cross compilation for more information.
