### ISSUE TITLE
max-length flag for limit of 32 needs to be set to 320

### ISSUE THREAD

**Issue by sjbuk** [jhaals/yopass#993]
Firstly great product really hits the mark.  

I want to use this to share passwords internally and therefore wanted to limit the message length to 32 characters.

In docker compose I set --max-length=32 and always got the message too long error.
Now with --max-length=320 it does limit the allowed message to 32 characters.

Current docker compose command is- command: "--max-length=320 --memcached=memcached:11211 --port=80"

**Comment by jhaals** [comment]
Hi! You can't really be that specific since the text is encrypted and ends up being a lot longer. You can make a custom build of the website and add client side length checks but it does not prevent anyone using the api directly. More info on the limits available in #1007
